version: '3.3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MY_SQL_PASSWORD}
      MYSQL_DATABASE: ${MY_SQL_DB_NAME}
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql # Persistent storage for database data
    ports:
      - 33066:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}:8080

  backend:
    build:
      context: .
      dockerfile: ./server/v1/DockerFile
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    container_name: node-app

volumes:
  mysql-data: # Define a named volume for persistent MySQL data
