FROM node:18

# Install chromium
RUN apt-get update \
    && apt-get install -y chromium \
    fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
    --no-install-recommends

# We don't need the standalone Chromium
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium

# Setting new folder in docker container where our files will be copied
# Setting user and group to node 
RUN mkdir -p /node/app/node_modules && chown -R node:node /node/app
#Switching to work dir
WORKDIR /node/app
#Copy just package jsons first to ensure correct dependency installations
COPY ./server/v1/package*.json ./

#Copy all other files from our local machine into the new folder in docker
COPY ./server/v1 .

# Install dependencies in the runtime image
RUN npm install --only=production

RUN npm install -g nodemon

# #FOR MIgrations
RUN npm install -g sequelize 

#Set User privileage using the application 
USER node

#Expose port that we can listen to
EXPOSE 5000
#RUN
CMD [ "npm","run", "server" ]